### PR TITLE
Feature/slack logging

### PR DESCRIPTION
**Pull request by estellerambier**
@gmguarino, this is a draft PR from your branch so that we can iterate from there.
Nice work! 
I have the following comments: 
- I took the freedom to run the repo [linting](https://github.com/dataforgoodfr/quotaclimat/blob/main/pyproject.toml#L51-L53) on your modifications
- Could you store the Slack token in the repo? I expected the Slack token to be a separate entity (an app), which was invited to the Slack workspace of D4G. Correct? As such, there is no security leak in sharing the secret key (considering the Slack of D4G as public). I am not 100% sure, we can run that by @TheoLvs first.

- Else, the main intent of the logging is to have it on the data ingestions jobs, [here](https://github.com/dataforgoodfr/quotaclimat/blob/main/quotaclimat/data_ingestion/scrap_sitemap.py#L101).

### CODE REVIEW

**Comment by gmguarino** [comment]
- If we add the token to the repo anyone can use it to message the channel we use for logging. If we are fine with this risk then there is no problem and we can add it. In any case we can just place them on the streamlit app secrets.toml file and retrieve them as environment variables.



- I can rework the logging in the ingestion jobs to the channel.
- We also have an issue of message redundancy at times: messages seem to arrive to the slack channel multiple times but I suspect it is a streamlit issue, so it will not affect ingestion logging.

**Comment by gmguarino** [comment]
rebased branch on main, removed logging from app

**Comment by gmguarino** [comment]
@estellerambier @TheoLvs What do you think about the token storage? It can go in the git or in the streamlit app, however you want. We just need to accept that if we put both token and channel in the code anyone can send a message but it seems like an acceptable risk.

**Comment by estellerambier** [comment]
Hey! I don't see the risk as:
- you grand only write access to the boot
- the D4G slack is public anyway.
It can go in the Streamlit app, but this will **not** work with the GitHub actions job, as they are an independent system. The jobs are triggered through GitHub itself, not the Streamlit

**Comment by gmguarino** [comment]
@estellerambier if this is ok for you I can merge the PR

**Comment by gmguarino** [comment]
image
The token has been deactivated. We need to find a way to store it securely

**Comment by gmguarino** [comment]
So when the token became public slack deactivated the app. I have reinstalled it to the workplace and created a new token.

We can store the token in the repository's **encrypted secrets**:

https://docs.github.com/en/actions/security-guides/encrypted-secrets

Whoever has repo owner access can add the new token to the github secrets and recover it during workflow execution like so:
```bash
env:
      SLACK_TOKEN: ${{ secrets.SuperSecret }}
```

**Comment by estellerambier** [comment]
Cool thank you! I will take a look tomorrow.

Did you trigger a error job on your branch to test out?

**Comment by gmguarino** [comment]
I can trigger locally but am unsure if I can trigger the gh action on a branch different to main?

**Pull request closed without merging**
